#define BINARY_AMPERSAND                 1
#define BINARY_AT                        2
#define BINARY_CARET                     3
#define BINARY_CONCAT                    4
#define BINARY_DOLLAR                    5
#define BINARY_EQUAL                     6
#define BINARY_HASH                      7
#define BINARY_MINUS                     8
#define BINARY_PERCENT                   9
#define BINARY_PERIOD                   10
#define BINARY_PIPE                     11
#define BINARY_PLUS                     12
#define BINARY_QUESTION                 13
#define BINARY_SLASH                    14
#define BINARY_STAR                     15
#define BINARY_TILDE                    16
#define COLON                           17
#define COMMA                           18
#define ERROR                           19
#define IDENTIFIER                      20
#define INTEGER                         21
#define L_ANGLE                         22
#define L_ANGLE_FAILURE                 23
#define L_ANGLE_SUCCESS                 24
#define L_PAREN                         25
#define L_PAREN_FAILURE                 26
#define L_PAREN_SUCCESS                 27
#define L_PAREN_WS                      28
#define L_SQUARE                        29
#define LABEL                           30
#define MATCH_DELETE                    31
#define MATCH_ONLY                      32
#define MATCH_REPLACE                   33
#define NULL                            34
#define OBJECT_DELETE                   35
#define OBJECT_REPLACE                  36
#define R_ANGLE                         37
#define R_PAREN                         38
#define R_SQUARE                        39
#define REAL                            40
#define SPACE                           41
#define STRING                          42
#define UNARY                           43
#define UNARY_EQUAL                     44
