#define BINARY_AMPERSAND                 1
#define BINARY_AT                        2
#define BINARY_CARET                     3
#define BINARY_DOLLAR                    4
#define BINARY_DOUBLE_STAR               5
#define BINARY_EQUAL                     6
#define BINARY_EXCLAMATION               7
#define BINARY_HASH                      8
#define BINARY_MINUS                     9
#define BINARY_PERCENT                  10
#define BINARY_PERIOD                   11
#define BINARY_PIPE                     12
#define BINARY_PLUS                     13
#define BINARY_QUESTION                 14
#define BINARY_SLASH                    15
#define BINARY_SPACE                    16
#define BINARY_STAR                     17
#define BINARY_TILDE                    18
#define COLON                           19
#define COMMA                           20
#define ERROR                           21
#define F                               22
#define IDENTIFIER                      23
#define INTEGER                         24
#define LABEL                           25
#define LEFT_ANGLE_BRACKET              26
#define LEFT_PAREN                      27
#define LEFT_SQUARE_BRACKET             28
#define MATCH_DELETE                    29
#define MATCH_ONLY                      30
#define MATCH_REPLACE                   31
#define NO_LABEL                        32
#define NULL                            33
#define OBJECT_DELETE                   34
#define OBJECT_REPLACE                  35
#define REAL                            36
#define RIGHT_ANGLE_BRACKET             37
#define RIGHT_PAREN                     38
#define RIGHT_SQUARE_BRACKET            39
#define S                               40
#define SPACE                           41
#define STRING                          42
#define UNARY_AMPERSAND                 43
#define UNARY_AT                        44
#define UNARY_CARET                     45
#define UNARY_DOLLAR                    46
#define UNARY_EQUAL                     47
#define UNARY_EXCLAMATION               48
#define UNARY_HASH                      49
#define UNARY_MINUS                     50
#define UNARY_PERCENT                   51
#define UNARY_PERIOD                    52
#define UNARY_PIPE                      53
#define UNARY_PLUS                      54
#define UNARY_QUESTION                  55
#define UNARY_SLASH                     56
#define UNARY_STAR                      57
#define UNARY_TILDE                     58
